version: '3'

services:
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./symfony-backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
