<?php
class Mock_route {
    private static function getUserData() {
        return [
            [
                "id" => "65a53f5285458e4e30a1b61e",
                "nom" => "AHMANE",
                "prenom" => "Hafid",
                "poste" => "Développeur",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/AHMANE-Hafid.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/AHMANE-Hafid.jpg",
                "nom_prenom" => "AHMANE Hafid"
            ],
            [
                "id" => "65a53f5285458e4e30a1b621",
                "nom" => "AULNETTE",
                "prenom" => "Philippe",
                "poste" => "Directeur Technique",
                "equipe" => "Team IT",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/AULNETTE-Philippe.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/AULNETTE-Philippe.jpg",
                "nom_prenom" => "AULNETTE Philippe"
            ],
            [
                "id" => "65a53f5285458e4e30a1b624",
                "nom" => "BEAUFILS",
                "prenom" => "Maud",
                "poste" => "Product Owner",
                "equipe" => "Pôle 8.6",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/BEAUFILS-Maud.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/BEAUFILS-Maud.jpg",
                "nom_prenom" => "BEAUFILS Maud"
            ],
            [
                "id" => "65a53f5285458e4e30a1b627",
                "nom" => "CASTEX",
                "prenom" => "David",
                "poste" => "Développeur",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CASTEX-David.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CASTEX-David.jpg",
                "nom_prenom" => "CASTEX David"
            ],
            [
                "id" => "65a53f5285458e4e30a1b629",
                "nom" => "CHEVALIER",
                "prenom" => "Elodie",
                "poste" => "Product Owner",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CHEVALIER-Elodie.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CHEVALIER-Elodie.jpg",
                "nom_prenom" => "CHEVALIER Elodie"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62c",
                "nom" => "COUTAND",
                "prenom" => "Bastien",
                "poste" => "Alternant",
                "equipe" => "Team IT",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "COUTAND Bastien"
            ],

            [
                "id" => "65a53f5285458e4e30a1b635",
                "nom" => "GANTOIS",
                "prenom" => "Emilien",
                "poste" => "Développeur",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GANTOIS-Emilien.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GANTOIS-Emilien.jpg",
                "nom_prenom" => "GANTOIS Emilien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b646",
                "nom" => "LEVASSEUR",
                "prenom" => "Damien",
                "poste" => "Développeur",
                "equipe" => "Team Eden",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LEVASSEUR-Damien.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LEVASSEUR-Damien.jpg",
                "nom_prenom" => "LEVASSEUR Damien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b654",
                "nom" => "QUENTEL",
                "prenom" => "Thomas",
                "poste" => "Développeur",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/QUENTEL-Thomas.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/QUENTEL-Thomas.jpg",
                "nom_prenom" => "QUENTEL Thomas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b655",
                "nom" => "RAMAUGE",
                "prenom" => "Benjamin",
                "poste" => "Développeur",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/RAMAUGE-Benjamin.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/RAMAUGE-Benjamin.jpg",
                "nom_prenom" => "RAMAUGE Benjamin"
            ],
            [
                "id" => "65a53f5285458e4e30a1b656",
                "nom" => "RENARD",
                "prenom" => "Valentin",
                "poste" => "Développeur",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/RENARD-Valentin.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/RENARD-Valentin.jpg",
                "nom_prenom" => "RENARD Valentin"
            ],
            [
                "id" => "65a53f5285458e4e30a1b657",
                "nom" => "ROUSSEAU",
                "prenom" => "Yoann",
                "poste" => "Développeur Junior",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/ROUSSEAU-Yoann.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/ROUSSEAU-Yoann.jpg",
                "nom_prenom" => "ROUSSEAU Yoann"
            ],
            [
                "id" => "65a53f5285458e4e30a1b65d",
                "nom" => "TOQUE",
                "prenom" => "Julien",
                "poste" => "Business Developer",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "TOQUE Julien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b661",
                "nom" => "VERON",
                "prenom" => "Maël",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle 8.6",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/VERON-Mael.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/VERON-Mael.jpg",
                "nom_prenom" => "VERON Maël"
            ],
            [
                "id" => "65a53f5285458e4e30a1b668",
                "nom" => "DURAND",
                "prenom" => "Guillaume",
                "poste" => "Développeur",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DURAND-Guillaume.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DURAND-Guillaume.jpg",
                "nom_prenom" => "DURAND Guillaume"
            ],
            [
                "id" => "65a53f5285458e4e30a1b675",
                "nom" => "PEAN",
                "prenom" => "Emilien",
                "poste" => "Responsable d'équipe",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/PEAN-Emilien.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/PEAN-Emilien.jpg",
                "nom_prenom" => "PEAN Emilien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b679",
                "nom" => "LE GOFF",
                "prenom" => "Jean-Marie",
                "poste" => "Coordinateur de projets",
                "equipe" => "Team Dev",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "LE GOFF Jean-Marie"
            ],
            [
                "id" => "65a53f5285458e4e30a1b67c",
                "nom" => "TAILLAND",
                "prenom" => "Gaelle",
                "poste" => "Cheffe de projet",
                "equipe" => "Team Dev",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "TAILLAND Gaelle"
            ],
            [
                "id" => "65a53f5285458e4e30a1b625",
                "nom" => "CANTEPIE",
                "prenom" => "Adrien",
                "poste" => "Développeur",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CANTEPIE-Adrien.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CANTEPIE-Adrien.jpg",
                "nom_prenom" => "CANTEPIE Adrien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b622",
                "nom" => "AVALIANI",
                "prenom" => "Ketevan",
                "poste" => "Assistante administrative",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "AVALIANI Ketevan"
            ],
            [
                "id" => "65a53f5285458e4e30a1b626",
                "nom" => "CARNEIRO",
                "prenom" => "Mickael",
                "poste" => "RSI",
                "equipe" => "Team IT",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CARNEIRO-Mickael.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CARNEIRO-Mickael.jpg",
                "nom_prenom" => "CARNEIRO Mickael"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62b",
                "nom" => "COET",
                "prenom" => "Jean",
                "poste" => "Développeur",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/COET-Jean.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/COET-Jean.jpg",
                "nom_prenom" => "COET Jean"
            ],
            [
                "id" => "65a53f5285458e4e30a1b631",
                "nom" => "DELENTE",
                "prenom" => "Edouard",
                "poste" => "Responsable Développement",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DELENTE-Edouard.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DELENTE-Edouard.jpg",
                "nom_prenom" => "DELENTE Edouard"
            ],
            [
                "id" => "65a53f5285458e4e30a1b633",
                "nom" => "DIGUET",
                "prenom" => "Lucas",
                "poste" => "Développeur",
                "equipe" => "Pôle 8.6",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DIGUET-Lucas.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DIGUET-Lucas.jpg",
                "nom_prenom" => "DIGUET Lucas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b634",
                "nom" => "FAILLIE",
                "prenom" => "Michel",
                "poste" => "Directeur de l'agence d'Angers",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/FAILLIE-Michel.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/FAILLIE-Michel.jpg",
                "nom_prenom" => "FAILLIE Michel"
            ],
            [
                "id" => "65a53f5285458e4e30a1b638",
                "nom" => "GINGUENEAU",
                "prenom" => "Pauline",
                "poste" => "Assistante Commerciale",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "GINGUENEAU Pauline"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63e",
                "nom" => "JUBLAN",
                "prenom" => "Sandrine",
                "poste" => "Assistante administrative",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/JUBLAN-Sandrine.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/JUBLAN-Sandrine.jpg",
                "nom_prenom" => "JUBLAN Sandrine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b644",
                "nom" => "LERAY",
                "prenom" => "Romain",
                "poste" => "Développeur",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LERAY-Romain.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LERAY-Romain.jpg",
                "nom_prenom" => "LERAY Romain"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64f",
                "nom" => "OZEAU",
                "prenom" => "Morgan",
                "poste" => "Développeur Senior",
                "equipe" => "Pôle 8.6",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/OZEAU-Morgan.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/OZEAU-Morgan.jpg",
                "nom_prenom" => "OZEAU Morgan"
            ],
            [
                "id" => "65a53f5285458e4e30a1b662",
                "nom" => "AUPIAIS",
                "prenom" => "David",
                "poste" => "Ingénieur Fullstack",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "AUPIAIS David"
            ],
            [
                "id" => "65a53f5285458e4e30a1b672",
                "nom" => "MAISONNEUVE",
                "prenom" => "Emmanuel",
                "poste" => "Directeur artistique",
                "equipe" => "Studio Design",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/MAISONNEUVE-Emmanuel.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/MAISONNEUVE-Emmanuel.jpg",
                "nom_prenom" => "MAISONNEUVE Emmanuel"
            ],
            [
                "id" => "65a53f5285458e4e30a1b673",
                "nom" => "MOREAU",
                "prenom" => "Maxime",
                "poste" => "Développeur",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/MOREAU-Maxime.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/MOREAU-Maxime.jpg",
                "nom_prenom" => "MOREAU Maxime"
            ],
            [
                "id" => "65a53f5285458e4e30a1b677",
                "nom" => "DOLLO",
                "prenom" => "Vincent",
                "poste" => "Développeur Mobile",
                "equipe" => "Team Dev",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "DOLLO Vincent"
            ],
            [
                "id" => "65a53f5285458e4e30a1b623",
                "nom" => "BAUDOT",
                "prenom" => "Tom",
                "poste" => "Développeur",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/BAUDOT-Tom.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/BAUDOT-Tom.jpg",
                "nom_prenom" => "BAUDOT Tom"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62a",
                "nom" => "CHEVALIER",
                "prenom" => "Benoît",
                "poste" => "Développeur",
                "equipe" => "Team Elephant",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "CHEVALIER Benoît"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62e",
                "nom" => "DANTAN",
                "prenom" => "Remy",
                "poste" => "Développeur",
                "equipe" => "Team Eden",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DANTAN-Remy.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DANTAN-Remy.jpg",
                "nom_prenom" => "DANTAN Remy"
            ],
            [
                "id" => "65a53f5285458e4e30a1b630",
                "nom" => "DELANOE",
                "prenom" => "Julien",
                "poste" => "Développeur",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "DELANOE Julien"
            ],
            [
                "id" => "65a53f5285458e4e30a1b636",
                "nom" => "GAUCHER",
                "prenom" => "Clara",
                "poste" => "Chef de Projet",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "GAUCHER Clara"
            ],
            [
                "id" => "65a53f5285458e4e30a1b637",
                "nom" => "GELEBART",
                "prenom" => "Nicolas",
                "poste" => "Business Manager",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "GELEBART Nicolas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b639",
                "nom" => "GOSSELIN",
                "prenom" => "Antoine",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "GOSSELIN Antoine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63b",
                "nom" => "GUERIN",
                "prenom" => "Nicolas",
                "poste" => "Développeur",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GUERIN-Nicolas.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GUERIN-Nicolas.jpg",
                "nom_prenom" => "GUERIN Nicolas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63d",
                "nom" => "JEZEQUEL",
                "prenom" => "Vincent",
                "poste" => "Responsable Technique",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/JEZEQUEL-Vincent.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/JEZEQUEL-Vincent.jpg",
                "nom_prenom" => "JEZEQUEL Vincent"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63f",
                "nom" => "LE COQ",
                "prenom" => "Alexandra",
                "poste" => "Comptable",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LE-COQ-Alexandra.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LE-COQ-Alexandra.jpg",
                "nom_prenom" => "LE COQ Alexandra"
            ],
            [
                "id" => "65a53f5285458e4e30a1b641",
                "nom" => "LECOLAZET",
                "prenom" => "Aymeric",
                "poste" => "Alternant",
                "equipe" => "Team Elephant",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LECOLAZET-Aymeric.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LECOLAZET-Aymeric.jpg",
                "nom_prenom" => "LECOLAZET Aymeric"
            ],
            [
                "id" => "65a53f5285458e4e30a1b642",
                "nom" => "LEGRAND",
                "prenom" => "Thomas",
                "poste" => "Responsable d'Equipe",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "LEGRAND Thomas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b649",
                "nom" => "LOUSTAU",
                "prenom" => "Quentin",
                "poste" => "Développeur",
                "equipe" => "Team Eden",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LOUSTAU-Quentin.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LOUSTAU-Quentin.jpg",
                "nom_prenom" => "LOUSTAU Quentin"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64a",
                "nom" => "LOUVEAU",
                "prenom" => "Bertille",
                "poste" => "Chargée de communication",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "LOUVEAU Bertille"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64c",
                "nom" => "MESLET",
                "prenom" => "Faustine",
                "poste" => "Talent Acquisition Specialist",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/MESLET-Faustine.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/MESLET-Faustine.jpg",
                "nom_prenom" => "MESLET Faustine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64e",
                "nom" => "OBEE",
                "prenom" => "Boris",
                "poste" => "Technicien Support",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/OBEE-Boris.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/OBEE-Boris.jpg",
                "nom_prenom" => "OBEE Boris"
            ],
            [
                "id" => "65a53f5285458e4e30a1b650",
                "nom" => "PERCHEREL",
                "prenom" => "Ludovic",
                "poste" => "Responsable d'équipe",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/PERCHEREL-Ludovic.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/PERCHEREL-Ludovic.jpg",
                "nom_prenom" => "PERCHEREL Ludovic"
            ],
            [
                "id" => "65a53f5285458e4e30a1b651",
                "nom" => "PERLINSKI",
                "prenom" => "Alix",
                "poste" => "Cheffe de projet",
                "equipe" => "Team Elephant",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "PERLINSKI Alix"
            ],
            [
                "id" => "65a53f5285458e4e30a1b652",
                "nom" => "POISSON",
                "prenom" => "Florian",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/POISSON-Florian.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/POISSON-Florian.jpg",
                "nom_prenom" => "POISSON Florian"
            ],
            [
                "id" => "65a53f5285458e4e30a1b659",
                "nom" => "SAUVE",
                "prenom" => "Karine",
                "poste" => "Directrice Administrative et Financière",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/SAUVE-Karine.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/SAUVE-Karine.jpg",
                "nom_prenom" => "SAUVE Karine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b65c",
                "nom" => "THOMAS",
                "prenom" => "Pierre-Yves",
                "poste" => "Développeur",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/THOMAS-Pierre-Yves.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/THOMAS-Pierre-Yves.jpg",
                "nom_prenom" => "THOMAS Pierre-Yves"
            ],
            [
                "id" => "65a53f5285458e4e30a1b65e",
                "nom" => "TREMIER",
                "prenom" => "Stéphane",
                "poste" => "Président",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/TREMIER-Stephane.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/TREMIER-Stephane.jpg",
                "nom_prenom" => "TREMIER Stéphane"
            ],
            [
                "id" => "65a53f5285458e4e30a1b663",
                "nom" => "BIORET",
                "prenom" => "Nicolas",
                "poste" => "Développeur",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "BIORET Nicolas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b665",
                "nom" => "CHENARD",
                "prenom" => "Renaud",
                "poste" => "Développeur",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CHENARD-Renaud.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CHENARD-Renaud.jpg",
                "nom_prenom" => "CHENARD Renaud"
            ],
            [
                "id" => "65a53f5285458e4e30a1b66b",
                "nom" => "GUERBAA",
                "prenom" => "Ines",
                "poste" => "Développeur",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GUERBAA-Ines.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GUERBAA-Ines.jpg",
                "nom_prenom" => "GUERBAA Ines"
            ],
            [
                "id" => "65a53f5285458e4e30a1b66d",
                "nom" => "JLAIEL",
                "prenom" => "Islem",
                "poste" => "Alternant",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "JLAIEL Islem"
            ],
            [
                "id" => "65a53f5285458e4e30a1b66f",
                "nom" => "KULESIAK",
                "prenom" => "Laura",
                "poste" => "Chef de projet",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/KULESIAK-Laura.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/KULESIAK-Laura.jpg",
                "nom_prenom" => "KULESIAK Laura"
            ],
            [
                "id" => "65a53f5285458e4e30a1b670",
                "nom" => "LEBEL",
                "prenom" => "Jérémy",
                "poste" => "Lead Developpeur",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LEBEL-Jeremy.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LEBEL-Jeremy.jpg",
                "nom_prenom" => "LEBEL Jérémy"
            ],
            [
                "id" => "65a53f5285458e4e30a1b671",
                "nom" => "LEMAITRE",
                "prenom" => "Mathieu",
                "poste" => "Chef de projet",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LEMAITRE-Mathieu.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LEMAITRE-Mathieu.jpg",
                "nom_prenom" => "LEMAITRE Mathieu"
            ],
            [
                "id" => "65a53f5285458e4e30a1b674",
                "nom" => "OBLE",
                "prenom" => "Maxime",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/OBLE-Maxime.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/OBLE-Maxime.jpg",
                "nom_prenom" => "OBLE Maxime"
            ],
            [
                "id" => "65a53f5285458e4e30a1b678",
                "nom" => "LANSONNEUR",
                "prenom" => "Thomas",
                "poste" => "UX/UI Designer",
                "equipe" => "Studio Design",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "LANSONNEUR Thomas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b61f",
                "nom" => "ANDRES",
                "prenom" => "Frédéric",
                "poste" => "Responsable d'équipe",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/ANDRES-Frederic.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/ANDRES-Frederic.jpg",
                "nom_prenom" => "ANDRES Frédéric"
            ],
            [
                "id" => "65a53f5285458e4e30a1b620",
                "nom" => "AUBRY",
                "prenom" => "Christophe",
                "poste" => "Développeur Senior",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "AUBRY Christophe"
            ],
            [
                "id" => "65a53f5285458e4e30a1b628",
                "nom" => "CHAPUIS",
                "prenom" => "Brice",
                "poste" => "Développeur",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "CHAPUIS Brice"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62d",
                "nom" => "CRUTEL",
                "prenom" => "Pauline",
                "poste" => "Chargée de recrutement",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/CRUTEL-Pauline.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/CRUTEL-Pauline.jpg",
                "nom_prenom" => "CRUTEL Pauline"
            ],
            [
                "id" => "65a53f5285458e4e30a1b62f",
                "nom" => "DE MONCUIT",
                "prenom" => "Gaëtan",
                "poste" => "Responsable Marketing",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DE-MONCUIT-Gaetan.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DE-MONCUIT-Gaetan.jpg",
                "nom_prenom" => "DE MONCUIT Gaëtan"
            ],
            [
                "id" => "65a53f5285458e4e30a1b632",
                "nom" => "DESGRANGES",
                "prenom" => "Pierre",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Position",
                "agence" => "Rennes",
                "photo_pro" => "",
                "photo_fun" => "",
                "nom_prenom" => "DESGRANGES Pierre"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63a",
                "nom" => "GREFFIER",
                "prenom" => "Jean-Christophe",
                "poste" => "Administrateur Système & Réseau",
                "equipe" => "Team IT",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GREFFIER-Jean-Christophe.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GREFFIER-Jean-Christophe.jpg",
                "nom_prenom" => "GREFFIER Jean-Christophe"
            ],
            [
                "id" => "65a53f5285458e4e30a1b63c",
                "nom" => "GUILBERT",
                "prenom" => "Antoine",
                "poste" => "Chef de Projet",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GUILBERT-Antoine.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GUILBERT-Antoine.jpg",
                "nom_prenom" => "GUILBERT Antoine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b640",
                "nom" => "LE GOFF",
                "prenom" => "Sébastien",
                "poste" => "Développeur Senior",
                "equipe" => "Bug Buster",
                "agence" => "Rennes",
                "nom_prenom" => "LE GOFF Sébastien",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b643",
                "nom" => "LEMARIE",
                "prenom" => "Benjamin",
                "poste" => "Design Manager",
                "equipe" => "Studio Design",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LEMARIE-Benjamin.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LEMARIE-Benjamin.jpg",
                "nom_prenom" => "LEMARIE Benjamin"
            ],
            [
                "id" => "65a53f5285458e4e30a1b645",
                "nom" => "LESAGE",
                "prenom" => "Olivier",
                "poste" => "Développeur Senior",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LESAGE-Olivier.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LESAGE-Olivier.jpg",
                "nom_prenom" => "LESAGE Olivier"
            ],
            [
                "id" => "65a53f5285458e4e30a1b647",
                "nom" => "LIDURIN",
                "prenom" => "Maël",
                "poste" => "Développeur / Chef de Projet",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LIDURIN-Mael.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LIDURIN-Mael.jpg",
                "nom_prenom" => "LIDURIN Maël"
            ],
            [
                "id" => "65a53f5285458e4e30a1b648",
                "nom" => "LOICHON",
                "prenom" => "Yvan",
                "poste" => "Intégrateur",
                "equipe" => "Studio Design",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/LOICHON-Yvan.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/LOICHON-Yvan.jpg",
                "nom_prenom" => "LOICHON Yvan"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64b",
                "nom" => "MADEC",
                "prenom" => "Florian",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/MADEC-Florian.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/MADEC-Florian.jpg",
                "nom_prenom" => "MADEC Florian"
            ],
            [
                "id" => "65a53f5285458e4e30a1b64d",
                "nom" => "MUSET",
                "prenom" => "Clément",
                "poste" => "Développeur",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/MUSET-Clement.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/MUSET-Clement.jpg",
                "nom_prenom" => "MUSET Clément"
            ],
            [
                "id" => "65a53f5285458e4e30a1b653",
                "nom" => "PRUD'HOMME",
                "prenom" => "Emilie",
                "poste" => "Cheffe de projet",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "nom_prenom" => "PRUD'HOMME Emilie",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b658",
                "nom" => "SAUVE",
                "prenom" => "Christophe",
                "poste" => "Chef de projet",
                "equipe" => "Pôle Cousteau",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/SAUVE-Christophe.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/SAUVE-Christophe.jpg",
                "nom_prenom" => "SAUVE Christophe"
            ],
            [
                "id" => "65a53f5285458e4e30a1b65a",
                "nom" => "SIMON",
                "prenom" => "Thomas",
                "poste" => "Responsable d'équipe",
                "equipe" => "Pôle Walker",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/SIMON-Thomas.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/SIMON-Thomas.jpg",
                "nom_prenom" => "SIMON Thomas"
            ],
            [
                "id" => "65a53f5285458e4e30a1b65b",
                "nom" => "TARLET",
                "prenom" => "Emeline",
                "poste" => "Alternant",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "nom_prenom" => "TARLET Emeline",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b65f",
                "nom" => "VANNIER",
                "prenom" => "Samuel",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle AI",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/VANNIER-Samuel.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/VANNIER-Samuel.jpg",
                "nom_prenom" => "VANNIER Samuel"
            ],
            [
                "id" => "65a53f5285458e4e30a1b660",
                "nom" => "VEILLAUX",
                "prenom" => "Pierre",
                "poste" => "Business Developer Junior",
                "equipe" => "Team Rocket",
                "agence" => "Rennes",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/VEILLAUX-Pierre.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/VEILLAUX-Pierre.jpg",
                "nom_prenom" => "VEILLAUX Pierre"
            ],
            [
                "id" => "65a53f5285458e4e30a1b664",
                "nom" => "BONTEMPS",
                "prenom" => "Quentin",
                "poste" => "Analyste développeur",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/BONTEMPS-Quentin.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/BONTEMPS-Quentin.jpg",
                "nom_prenom" => "BONTEMPS Quentin"
            ],
            [
                "id" => "65a53f5285458e4e30a1b666",
                "nom" => "DELCROS",
                "prenom" => "Cédric",
                "poste" => "Chef de projet / Responsable d'équipe",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/DELCROS-Cedric.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/DELCROS-Cedric.jpg",
                "nom_prenom" => "DELCROS Cédric"
            ],
            [
                "id" => "65a53f5285458e4e30a1b667",
                "nom" => "DELEVALLEZ",
                "prenom" => "Zacharie",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "nom_prenom" => "DELEVALLEZ Zacharie",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b669",
                "nom" => "GIRARD",
                "prenom" => "Amaury",
                "poste" => "Développeur",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GIRARD-Amaury.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GIRARD-Amaury.jpg",
                "nom_prenom" => "GIRARD Amaury"
            ],
            [
                "id" => "65a53f5285458e4e30a1b66a",
                "nom" => "GARRETA",
                "prenom" => "Antoine",
                "poste" => "Développeur Junior",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "photo_pro" => "https://trombi.6tmphp.fr/images/pro/GARRETA-Antoine.jpg",
                "photo_fun" => "https://trombi.6tmphp.fr/images/fun/GARRETA-Antoine.jpg",
                "nom_prenom" => "GARRETA Antoine"
            ],
            [
                "id" => "65a53f5285458e4e30a1b66c",
                "nom" => "HAMON",
                "prenom" => "Kévin",
                "poste" => "Développeur",
                "equipe" => "Pôle Passe Partout",
                "agence" => "Angers",
                "nom_prenom" => "HAMON Kévin",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b66e",
                "nom" => "KOBAA",
                "prenom" => "Marwen",
                "poste" => "Développeur",
                "equipe" => "Pôle Griffondor",
                "agence" => "Angers",
                "nom_prenom" => "KOBAA Marwen",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b676",
                "nom" => "BENSI",
                "prenom" => "Louis",
                "poste" => "Développeur Front",
                "equipe" => "Studio Design",
                "agence" => "Rennes",
                "nom_prenom" => "BENSI Louis",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b67a",
                "nom" => "LE MEE",
                "prenom" => "Antonin",
                "poste" => "Développeur",
                "equipe" => "Team Dev",
                "agence" => "Rennes",
                "nom_prenom" => "LE MEE Antonin",
                "photo_pro" => "",
                "photo_fun" => ""
            ],
            [
                "id" => "65a53f5285458e4e30a1b67b",
                "nom" => "SACHET",
                "prenom" => "Mathieu",
                "poste" => "Lead Developpeur",
                "equipe" => "Team Dev",
                "agence" => "Rennes",
                "nom_prenom" => "SACHET Mathieu",
                "photo_pro" => "",
                "photo_fun" => ""
            ]
        ];
    }

    public static function handleRequest() {
        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
            $userData = self::getUserData();

            header('Content-Type: application/json');
            echo json_encode($userData);
                exit;
        }
    }
}

Mock_route::handleRequest();