controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

my_route:
    path: /my-route
    controller: App\Controller\YourController::yourAction
