controllers:
    resource: ../src/Controller/
    namespace: App\Controller
    type: attribute

get_user:
    path: /users/{full_name}
    controller: UserController::getUser
    methods: ['GET']

add_user:
    path: /users
    controller: UserController::addUser
    methods: ['POST']

edit_user:
    path: /users/{full_name}
    controller: UserController::editUser
    methods: ['PUT']

delete_user:
    path: /users/{full_name}
    controller: UserController::deleteUser
    methods: ['DELETE']
